// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb2tyBkY5nLgGgMoOGhUVJzBAVEB5CYB0',
    appId: '1:1089907796570:web:2c28eeca3338cfa66b8663',
    messagingSenderId: '1089907796570',
    projectId: 'gonort-tech',
    authDomain: 'gonort-tech.firebaseapp.com',
    storageBucket: 'gonort-tech.firebasestorage.app',
    measurementId: 'G-DY0GN4W6WK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAndntK-poQq2WsaxFvZNMP3BhQtGdZMbU',
    appId: '1:1089907796570:android:0c15e5bda9079b786b8663',
    messagingSenderId: '1089907796570',
    projectId: 'gonort-tech',
    storageBucket: 'gonort-tech.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGwo0VRIeU3rD583aVORr8Mi1mq6BTSb0',
    appId: '1:1089907796570:ios:489e48e325c61f966b8663',
    messagingSenderId: '1089907796570',
    projectId: 'gonort-tech',
    storageBucket: 'gonort-tech.firebasestorage.app',
    iosClientId: '1089907796570-pghesikk7tcuhaiggahlb2hegvd49pou.apps.googleusercontent.com',
    iosBundleId: 'com.example.flComponents',
  );
}
